# train.sub 
universe = vanilla
requirements = (OpSysMajorVer == 8) && ((PoolName == "CHTC") || (SINGULARITY_CAN_USE_SIF))
+SingularityImage = "train.sif"

executable = train.sh
arguments = $(job_num) $(config_start) $(config_end)

log = $(Cluster).log
error = error/error_$(job_num).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_remaps = "results_$(job_num).csv = results/results_$(job_num).csv"
on_exit_hold = exitcode != 0
max_retries = 1
